"""add foreign key to Review model

Revision ID: 633a4d5a2c1b
Revises: b0df9511c45c
Create Date: 2024-11-19 17:48:58.670759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '633a4d5a2c1b'
down_revision = 'b0df9511c45c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('employee_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_reviews_employee_id_employees'), 'reviews', 'employees', ['employee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_reviews_employee_id_employees'), 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'employee_id')
    # ### end Alembic commands ###
